// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(TrafilaturaFFI)
import TrafilaturaFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_trafilatura_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_trafilatura_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTrafilaturaUniffiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * Extraction result containing content, comments, and metadata.
 */
public struct ExtractResult: Equatable, Hashable {
    public var contentText: String
    public var commentsText: String
    public var contentHtml: String
    public var commentsHtml: String
    public var metadata: Metadata

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(contentText: String, commentsText: String, contentHtml: String, commentsHtml: String, metadata: Metadata) {
        self.contentText = contentText
        self.commentsText = commentsText
        self.contentHtml = contentHtml
        self.commentsHtml = commentsHtml
        self.metadata = metadata
    }

    

    
}

#if compiler(>=6)
extension ExtractResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeExtractResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ExtractResult {
        return
            try ExtractResult(
                contentText: FfiConverterString.read(from: &buf), 
                commentsText: FfiConverterString.read(from: &buf), 
                contentHtml: FfiConverterString.read(from: &buf), 
                commentsHtml: FfiConverterString.read(from: &buf), 
                metadata: FfiConverterTypeMetadata.read(from: &buf)
        )
    }

    public static func write(_ value: ExtractResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.contentText, into: &buf)
        FfiConverterString.write(value.commentsText, into: &buf)
        FfiConverterString.write(value.contentHtml, into: &buf)
        FfiConverterString.write(value.commentsHtml, into: &buf)
        FfiConverterTypeMetadata.write(value.metadata, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExtractResult_lift(_ buf: RustBuffer) throws -> ExtractResult {
    return try FfiConverterTypeExtractResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExtractResult_lower(_ value: ExtractResult) -> RustBuffer {
    return FfiConverterTypeExtractResult.lower(value)
}


/**
 * Advanced tuning parameters.
 */
public struct ExtractionConfig: Equatable, Hashable {
    public var minExtractedSize: Int32
    public var minExtractedCommentSize: Int32
    public var minOutputSize: Int32
    public var minOutputCommentSize: Int32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(minExtractedSize: Int32, minExtractedCommentSize: Int32, minOutputSize: Int32, minOutputCommentSize: Int32) {
        self.minExtractedSize = minExtractedSize
        self.minExtractedCommentSize = minExtractedCommentSize
        self.minOutputSize = minOutputSize
        self.minOutputCommentSize = minOutputCommentSize
    }

    

    
}

#if compiler(>=6)
extension ExtractionConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeExtractionConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ExtractionConfig {
        return
            try ExtractionConfig(
                minExtractedSize: FfiConverterInt32.read(from: &buf), 
                minExtractedCommentSize: FfiConverterInt32.read(from: &buf), 
                minOutputSize: FfiConverterInt32.read(from: &buf), 
                minOutputCommentSize: FfiConverterInt32.read(from: &buf)
        )
    }

    public static func write(_ value: ExtractionConfig, into buf: inout [UInt8]) {
        FfiConverterInt32.write(value.minExtractedSize, into: &buf)
        FfiConverterInt32.write(value.minExtractedCommentSize, into: &buf)
        FfiConverterInt32.write(value.minOutputSize, into: &buf)
        FfiConverterInt32.write(value.minOutputCommentSize, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExtractionConfig_lift(_ buf: RustBuffer) throws -> ExtractionConfig {
    return try FfiConverterTypeExtractionConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExtractionConfig_lower(_ value: ExtractionConfig) -> RustBuffer {
    return FfiConverterTypeExtractionConfig.lower(value)
}


/**
 * Extraction options.
 */
public struct ExtractionOptions: Equatable, Hashable {
    public var config: ExtractionConfig
    /**
     * Page URL as string, or empty.
     */
    public var originalUrl: String?
    /**
     * ISO 639-1 language code to enforce.
     */
    public var targetLanguage: String?
    public var enableFallback: Bool
    public var focus: ExtractionFocus
    public var excludeComments: Bool
    public var excludeTables: Bool
    public var includeImages: Bool
    public var includeLinks: Bool
    public var deduplicate: Bool
    public var requireEssentialMetadata: Bool
    public var maxTreeSize: Int64?
    /**
     * CSS selector for pre-pruning elements.
     */
    public var pruneSelector: String?
    public var htmlDateMode: HtmlDateMode
    /**
     * Date override as ISO-8601 string (YYYY-MM-DD), or empty.
     */
    public var htmlDateOverride: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(config: ExtractionConfig, 
        /**
         * Page URL as string, or empty.
         */originalUrl: String?, 
        /**
         * ISO 639-1 language code to enforce.
         */targetLanguage: String?, enableFallback: Bool, focus: ExtractionFocus, excludeComments: Bool, excludeTables: Bool, includeImages: Bool, includeLinks: Bool, deduplicate: Bool, requireEssentialMetadata: Bool, maxTreeSize: Int64?, 
        /**
         * CSS selector for pre-pruning elements.
         */pruneSelector: String?, htmlDateMode: HtmlDateMode, 
        /**
         * Date override as ISO-8601 string (YYYY-MM-DD), or empty.
         */htmlDateOverride: String?) {
        self.config = config
        self.originalUrl = originalUrl
        self.targetLanguage = targetLanguage
        self.enableFallback = enableFallback
        self.focus = focus
        self.excludeComments = excludeComments
        self.excludeTables = excludeTables
        self.includeImages = includeImages
        self.includeLinks = includeLinks
        self.deduplicate = deduplicate
        self.requireEssentialMetadata = requireEssentialMetadata
        self.maxTreeSize = maxTreeSize
        self.pruneSelector = pruneSelector
        self.htmlDateMode = htmlDateMode
        self.htmlDateOverride = htmlDateOverride
    }

    

    
}

#if compiler(>=6)
extension ExtractionOptions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeExtractionOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ExtractionOptions {
        return
            try ExtractionOptions(
                config: FfiConverterTypeExtractionConfig.read(from: &buf), 
                originalUrl: FfiConverterOptionString.read(from: &buf), 
                targetLanguage: FfiConverterOptionString.read(from: &buf), 
                enableFallback: FfiConverterBool.read(from: &buf), 
                focus: FfiConverterTypeExtractionFocus.read(from: &buf), 
                excludeComments: FfiConverterBool.read(from: &buf), 
                excludeTables: FfiConverterBool.read(from: &buf), 
                includeImages: FfiConverterBool.read(from: &buf), 
                includeLinks: FfiConverterBool.read(from: &buf), 
                deduplicate: FfiConverterBool.read(from: &buf), 
                requireEssentialMetadata: FfiConverterBool.read(from: &buf), 
                maxTreeSize: FfiConverterOptionInt64.read(from: &buf), 
                pruneSelector: FfiConverterOptionString.read(from: &buf), 
                htmlDateMode: FfiConverterTypeHtmlDateMode.read(from: &buf), 
                htmlDateOverride: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ExtractionOptions, into buf: inout [UInt8]) {
        FfiConverterTypeExtractionConfig.write(value.config, into: &buf)
        FfiConverterOptionString.write(value.originalUrl, into: &buf)
        FfiConverterOptionString.write(value.targetLanguage, into: &buf)
        FfiConverterBool.write(value.enableFallback, into: &buf)
        FfiConverterTypeExtractionFocus.write(value.focus, into: &buf)
        FfiConverterBool.write(value.excludeComments, into: &buf)
        FfiConverterBool.write(value.excludeTables, into: &buf)
        FfiConverterBool.write(value.includeImages, into: &buf)
        FfiConverterBool.write(value.includeLinks, into: &buf)
        FfiConverterBool.write(value.deduplicate, into: &buf)
        FfiConverterBool.write(value.requireEssentialMetadata, into: &buf)
        FfiConverterOptionInt64.write(value.maxTreeSize, into: &buf)
        FfiConverterOptionString.write(value.pruneSelector, into: &buf)
        FfiConverterTypeHtmlDateMode.write(value.htmlDateMode, into: &buf)
        FfiConverterOptionString.write(value.htmlDateOverride, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExtractionOptions_lift(_ buf: RustBuffer) throws -> ExtractionOptions {
    return try FfiConverterTypeExtractionOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExtractionOptions_lower(_ value: ExtractionOptions) -> RustBuffer {
    return FfiConverterTypeExtractionOptions.lower(value)
}


/**
 * Document metadata extracted from HTML.
 */
public struct Metadata: Equatable, Hashable {
    public var title: String
    public var author: String
    public var url: String
    public var hostname: String
    public var description: String
    public var sitename: String
    /**
     * ISO-8601 date string (YYYY-MM-DD) or empty.
     */
    public var date: String?
    public var categories: [String]
    public var tags: [String]
    public var id: String
    public var fingerprint: String
    public var license: String
    public var language: String
    public var image: String
    public var pageType: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(title: String, author: String, url: String, hostname: String, description: String, sitename: String, 
        /**
         * ISO-8601 date string (YYYY-MM-DD) or empty.
         */date: String?, categories: [String], tags: [String], id: String, fingerprint: String, license: String, language: String, image: String, pageType: String) {
        self.title = title
        self.author = author
        self.url = url
        self.hostname = hostname
        self.description = description
        self.sitename = sitename
        self.date = date
        self.categories = categories
        self.tags = tags
        self.id = id
        self.fingerprint = fingerprint
        self.license = license
        self.language = language
        self.image = image
        self.pageType = pageType
    }

    

    
}

#if compiler(>=6)
extension Metadata: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Metadata {
        return
            try Metadata(
                title: FfiConverterString.read(from: &buf), 
                author: FfiConverterString.read(from: &buf), 
                url: FfiConverterString.read(from: &buf), 
                hostname: FfiConverterString.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                sitename: FfiConverterString.read(from: &buf), 
                date: FfiConverterOptionString.read(from: &buf), 
                categories: FfiConverterSequenceString.read(from: &buf), 
                tags: FfiConverterSequenceString.read(from: &buf), 
                id: FfiConverterString.read(from: &buf), 
                fingerprint: FfiConverterString.read(from: &buf), 
                license: FfiConverterString.read(from: &buf), 
                language: FfiConverterString.read(from: &buf), 
                image: FfiConverterString.read(from: &buf), 
                pageType: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Metadata, into buf: inout [UInt8]) {
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.author, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.hostname, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterString.write(value.sitename, into: &buf)
        FfiConverterOptionString.write(value.date, into: &buf)
        FfiConverterSequenceString.write(value.categories, into: &buf)
        FfiConverterSequenceString.write(value.tags, into: &buf)
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.fingerprint, into: &buf)
        FfiConverterString.write(value.license, into: &buf)
        FfiConverterString.write(value.language, into: &buf)
        FfiConverterString.write(value.image, into: &buf)
        FfiConverterString.write(value.pageType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMetadata_lift(_ buf: RustBuffer) throws -> Metadata {
    return try FfiConverterTypeMetadata.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMetadata_lower(_ value: Metadata) -> RustBuffer {
    return FfiConverterTypeMetadata.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Extraction strategy.
 */

public enum ExtractionFocus: Equatable, Hashable {
    
    case balanced
    case favorRecall
    case favorPrecision





}

#if compiler(>=6)
extension ExtractionFocus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeExtractionFocus: FfiConverterRustBuffer {
    typealias SwiftType = ExtractionFocus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ExtractionFocus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .balanced
        
        case 2: return .favorRecall
        
        case 3: return .favorPrecision
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ExtractionFocus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .balanced:
            writeInt(&buf, Int32(1))
        
        
        case .favorRecall:
            writeInt(&buf, Int32(2))
        
        
        case .favorPrecision:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExtractionFocus_lift(_ buf: RustBuffer) throws -> ExtractionFocus {
    return try FfiConverterTypeExtractionFocus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExtractionFocus_lower(_ value: ExtractionFocus) -> RustBuffer {
    return FfiConverterTypeExtractionFocus.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Date extraction mode.
 */

public enum HtmlDateMode: Equatable, Hashable {
    
    case automatic
    case fast
    case extensive
    case disabled





}

#if compiler(>=6)
extension HtmlDateMode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHtmlDateMode: FfiConverterRustBuffer {
    typealias SwiftType = HtmlDateMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HtmlDateMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .automatic
        
        case 2: return .fast
        
        case 3: return .extensive
        
        case 4: return .disabled
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HtmlDateMode, into buf: inout [UInt8]) {
        switch value {
        
        
        case .automatic:
            writeInt(&buf, Int32(1))
        
        
        case .fast:
            writeInt(&buf, Int32(2))
        
        
        case .extensive:
            writeInt(&buf, Int32(3))
        
        
        case .disabled:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHtmlDateMode_lift(_ buf: RustBuffer) throws -> HtmlDateMode {
    return try FfiConverterTypeHtmlDateMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHtmlDateMode_lower(_ value: HtmlDateMode) -> RustBuffer {
    return FfiConverterTypeHtmlDateMode.lower(value)
}



/**
 * Errors returned by extraction functions.
 */
public enum TrafilaturaError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case ParseError(reason: String
    )
    case LanguageMismatch(expected: String, got: String
    )
    case InsufficientContent(reason: String
    )
    case MissingMetadata(reason: String
    )
    case DuplicateContent
    case TreeTooLarge(size: Int64
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension TrafilaturaError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTrafilaturaError: FfiConverterRustBuffer {
    typealias SwiftType = TrafilaturaError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TrafilaturaError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ParseError(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 2: return .LanguageMismatch(
            expected: try FfiConverterString.read(from: &buf), 
            got: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InsufficientContent(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 4: return .MissingMetadata(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 5: return .DuplicateContent
        case 6: return .TreeTooLarge(
            size: try FfiConverterInt64.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TrafilaturaError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ParseError(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .LanguageMismatch(expected,got):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(expected, into: &buf)
            FfiConverterString.write(got, into: &buf)
            
        
        case let .InsufficientContent(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .MissingMetadata(reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)
            
        
        case .DuplicateContent:
            writeInt(&buf, Int32(5))
        
        
        case let .TreeTooLarge(size):
            writeInt(&buf, Int32(6))
            FfiConverterInt64.write(size, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrafilaturaError_lift(_ buf: RustBuffer) throws -> TrafilaturaError {
    return try FfiConverterTypeTrafilaturaError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrafilaturaError_lower(_ value: TrafilaturaError) -> RustBuffer {
    return FfiConverterTypeTrafilaturaError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
/**
 * Create a self-contained HTML document from an extraction result.
 */
public func createReadableDocument(result: ExtractResult) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_trafilatura_uniffi_fn_func_create_readable_document(
        FfiConverterTypeExtractResult_lower(result),$0
    )
})
}
/**
 * Returns the default extraction config.
 */
public func defaultConfig() -> ExtractionConfig  {
    return try!  FfiConverterTypeExtractionConfig_lift(try! rustCall() {
    uniffi_trafilatura_uniffi_fn_func_default_config($0
    )
})
}
/**
 * Returns the default extraction options.
 */
public func defaultOptions() -> ExtractionOptions  {
    return try!  FfiConverterTypeExtractionOptions_lift(try! rustCall() {
    uniffi_trafilatura_uniffi_fn_func_default_options($0
    )
})
}
/**
 * Extract content from HTML with custom options.
 */
public func extract(html: String, options: ExtractionOptions)throws  -> ExtractResult  {
    return try  FfiConverterTypeExtractResult_lift(try rustCallWithError(FfiConverterTypeTrafilaturaError_lift) {
    uniffi_trafilatura_uniffi_fn_func_extract(
        FfiConverterString.lower(html),
        FfiConverterTypeExtractionOptions_lower(options),$0
    )
})
}
/**
 * Extract content from HTML with default options.
 */
public func extractSimple(html: String)throws  -> ExtractResult  {
    return try  FfiConverterTypeExtractResult_lift(try rustCallWithError(FfiConverterTypeTrafilaturaError_lift) {
    uniffi_trafilatura_uniffi_fn_func_extract_simple(
        FfiConverterString.lower(html),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_trafilatura_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_trafilatura_uniffi_checksum_func_create_readable_document() != 55663) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_trafilatura_uniffi_checksum_func_default_config() != 29638) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_trafilatura_uniffi_checksum_func_default_options() != 23313) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_trafilatura_uniffi_checksum_func_extract() != 58272) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_trafilatura_uniffi_checksum_func_extract_simple() != 21108) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTrafilaturaUniffiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all